TP03/TP3_HerreraLeonel/Controllers/CadeteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TP3_HerreraLeonel.Models;
using TP3_HerreraLeonel.Entities;
using TP3_HerreraLeonel.ViewModels;
using Microsoft.AspNetCore.Http;
using AutoMapper;

namespace TP3_HerreraLeonel.Controllers
{
    public class CadeteController : Controller
    {
        private readonly IDataBase DB;
        private readonly IMapper mapper;
       
        public CadeteController(IDataBase dataBase, IMapper autoMap)
        {
            DB = dataBase;
            mapper = autoMap;
        }
        
        public IActionResult Index()
        {
            try {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UsuarioMV = mapper.Map<IndexViewModel>(user);
                var CadetesMV = mapper.Map<List<CadeteIndexViewModel>>(DB.RepoCadete_Sqlite.getAll());
                if (UsuarioMV.Username != null)
                {
                    return View(new Tuple<List<CadeteIndexViewModel>,IndexViewModel>(CadetesMV, UsuarioMV));
                }
                else
                {
                    return Redirect("~/Usuario/Login");
                }
            }
            catch (Exception){
                return Redirect("~/Usuario/Login");
            }            
        }
        
        //Vista de los pedidos asignados a cada cadete
        public IActionResult ListPedidos(int id)
        {
            List<Cadete> ListCadetes = DB.RepoCadete_Sqlite.getAll();
            
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UsuarioMV = mapper.Map<IndexViewModel>(user);
                var CadeteMV = mapper.Map<CadeteIndexViewModel>(ListCadetes.Where(cad => cad.Id == id).Single());
                if (UsuarioMV.Username != null && UsuarioMV.Username =="admin")
                {
                    return View(new Tuple<CadeteIndexViewModel, IndexViewModel>( CadeteMV, UsuarioMV));
                }
                if (UsuarioMV.Username != null)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Redirect("~/Usuario/Login");
                }
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return Redirect("~/Cadete");
            }
        }

        //Alta de Cadete 
        public IActionResult AltaCadete()
        {
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UsuarioMV = mapper.Map<IndexViewModel>(user);

                if (UsuarioMV.Username != null && UsuarioMV.Username == "admin")
                {
                    var CadeteVM = new CadeteAltaViewModel();
                    CadeteVM.UsuarioLog = UsuarioMV;
                    return View(CadeteVM);
                }
                else if (UsuarioMV.Username != null)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }

            }
            catch (Exception)
            {
                return Redirect("~/Usuario/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AltaCadete(CadeteAltaViewModel CadeteVM)
        {
            
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                CadeteVM.UsuarioLog = mapper.Map<IndexViewModel>(user);

                if (CadeteVM.UsuarioLog != null && ModelState.IsValid)
                {
                    Cadete nuevoCadete = mapper.Map<Cadete>(CadeteVM);
                    DB.RepoCadete_Sqlite.InsertCadetes(nuevoCadete);//Inserto en la DB
                    DB.RepoCadete_Json.InsertCadetes(nuevoCadete);//Inserto en el Archivo Json
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }

            }
            catch (Exception)
            {
                return Redirect("~/Usuario/Login");
            }
        }

        
        //Muestro los datos del cadete en el form de edicion
        public IActionResult ModificarCadete(int id)
        {
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UsuarioMV = mapper.Map<IndexViewModel>(user);
                
                if (UsuarioMV.Username != null && UsuarioMV.Username =="admin")
                {
                    var cadeteADevolver = mapper.Map<CadeteModificarViewModel>(DB.RepoCadete_Sqlite.getCadeteAModificar(id));
                    cadeteADevolver.UsuarioLog = UsuarioMV;

                    if (cadeteADevolver != null)
                        return View(cadeteADevolver);
                    else
                        return Redirect("~/Cadete");
                }
                else if (UsuarioMV.Username != null) {

                    return RedirectToAction("Index");
                }
                else
                {
                    return Redirect("~/Usuario/Login");
                }
            }
            catch (Exception) { return Redirect("~/Usuario/Login"); }       
        }

        //Modifico los datos del cadete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ModificarCadete(CadeteModificarViewModel CadeteVM)
        {
            if (ModelState.IsValid && CadeteVM.Id > 0)
            {
                var cadeteAModificar = mapper.Map<Cadete>(CadeteVM);
                DB.RepoCadete_Sqlite.UpdateCadetes(cadeteAModificar);
                DB.RepoCadete_Json.UpdateCadetes(cadeteAModificar);
                return Redirect("~/Cadete");
            }
            return RedirectToAction("Error");
            
        }
        
        //Elimino el cadete
        public IActionResult EliminarCadete(int id)
        {
            if (HttpContext.Session.GetString("username") == "admin") {
                DB.RepoCadete_Sqlite.DeleteCadetes(id);
                DB.RepoCadete_Json.DeleteCadetes(id);
            }
           
            return Redirect("~/Cadete");
        }

        //Elimino todos los cadetes
        public IActionResult DeleteAll_Cadetes()
        {
            if (HttpContext.Session.GetString("username") == "admin")
            {
                DB.RepoCadete_Sqlite.DeleteAllCadetes();
                DB.RepoCadete_Json.DeleteAllCadetes();
            }
               
            return Redirect("~/Cadete");
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TP03/TP3_HerreraLeonel/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TP3_HerreraLeonel.Models;
using TP3_HerreraLeonel.Entities;
using TP3_HerreraLeonel.ViewModels;
using Microsoft.AspNetCore.Http;
using AutoMapper;


namespace TP3_HerreraLeonel.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IDataBase DB;

        private readonly IMapper mapper;

        public PedidoController(IDataBase dataBase, IMapper autoMap)
        {
            DB = dataBase;
            mapper = autoMap;
        }
        
        public IActionResult Index()
        {
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UserVM = mapper.Map<IndexViewModel>(user);
                if (UserVM.Username != null)
                {
                    var ListPedidos = mapper.Map<List<PedidoIndexViewModel>>(DB.RepoPedido_Sqlite.getAllPedidos());
                    
                    foreach (var ped in ListPedidos)
                    {
                        var _pedido = mapper.Map<Pedido>(ped);
                        ped.getCadete = mapper.Map<CadeteIndexViewModel>(DB.RepoPedido_Sqlite.get_Only_Pedido_delCadete(_pedido));
                    }
                    return View(new Tuple<List<PedidoIndexViewModel>, IndexViewModel>(ListPedidos, UserVM));
                }
                else
                {
                    return Redirect("~/Usuario/Login");
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
                return Redirect("~/Usuario/Login");
            }
        }


        //Alta de pedidos
        public IActionResult AltaPedido()
        {
            try
            {
                Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                var UserVM = mapper.Map<IndexViewModel>(user);
                if (UserVM.Username != null && UserVM.Username =="admin")
                {
                    var ListCadetes = mapper.Map<List<CadeteIndexViewModel>>(DB.RepoCadete_Sqlite.getAll());
                    AltaPedidoViewModel PedidoVM = new AltaPedidoViewModel();
                    PedidoVM.UsuarioLog = UserVM;
                    PedidoVM.ListaCadetes = ListCadetes;
                    return View(PedidoVM);
                }
                else if (UserVM.Username != null)
                {
                    
                    return RedirectToAction("Index");
                }
                else
                {
                    return Redirect("~/Usuario/Login");
                }
            }
            catch (Exception)
            {
                return Redirect("~/Usuario/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AltaPedido(AltaPedidoViewModel PedidoVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var nuevoPedido = mapper.Map<Pedido>(PedidoVM);
                    Cadete cadeteSeleccionado = DB.RepoCadete_Sqlite.getCadeteAModificar(PedidoVM.idCadete);
                    DB.RepoPedido_Sqlite.InsertPedidos(nuevoPedido, cadeteSeleccionado.Id);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }         
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return Redirect("~/Usuario/Login");
            }
        }
        

         //Muestro el pedido a modificar en el form
         public IActionResult ModificarPedido(int id)
         {
             try
             {
                 Usuario user = DB.RepoUsuario_Sqlite.LoginUser(HttpContext.Session.GetString("username"));
                 var UserVM = mapper.Map<IndexViewModel>(user);
                 if (UserVM.Username != null && UserVM.Username =="admin")
                 {
                    var ListCadetes = mapper.Map<List<CadeteIndexViewModel>>(DB.RepoCadete_Sqlite.getAll());
                    var pedidoADevolver = mapper.Map<PedidoIndexViewModel>(DB.RepoPedido_Sqlite.getPedidoAModificar(id));
                     if (pedidoADevolver != null)
                     {
                        ModificarPedidoViewModel modificar = new ModificarPedidoViewModel
                        {
                            UsuarioLog = UserVM,
                            ListaCadetes = ListCadetes,
                            Nro = pedidoADevolver.Nro,
                            Observacion = pedidoADevolver.Observacion,
                            Estado = (ModificarPedidoViewModel.Estados)Enum.Parse(typeof(ModificarPedidoViewModel.Estados), pedidoADevolver.Estado.ToString()) ,
                            Cliente = pedidoADevolver.Cliente,
                         };
                        
                         return View(modificar);
                     }

                     else
                         return Redirect("~/Pedido");
                 }
                 else if (UserVM.Username != null) {
                    return Redirect("~/Pedido");
                 }
                 else
                 {
                     return Redirect("~/Usuario/Login");
                 }

             }
             catch (Exception) {
                 return Redirect("~/Usuario/Login");
             }
         }

        //Modifico los datos del pedido
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ModificarPedido(ModificarPedidoViewModel PedidoVM)
         {
             if (ModelState.IsValid)
             {
                Pedido pedidoADevolver = mapper.Map<Pedido>(PedidoVM);
                DB.RepoPedido_Sqlite.UpdatePedidos(pedidoADevolver, PedidoVM.idCadete);
                return Redirect("~/Pedido");
            }
            return RedirectToAction("Error");
         }
         
        //Elimino un pedido
        public IActionResult EliminarPedido(int id)
        {
            if (HttpContext.Session.GetString("username") == "admin") {
                DB.RepoPedido_Sqlite.DeletePedido(id);
            }
            return Redirect("~/Pedido");
        }

        //Elimino todos los pedidos
        public IActionResult DeleteAll_Pedidos()
        {
            if (HttpContext.Session.GetString("username") == "admin")
            {
                DB.RepoPedido_Sqlite.DeleteAllPedidos();
            }
            return Redirect("~/Pedido");
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TP03/TP3_HerreraLeonel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadeteria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <br />
    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2021 - TP3_HerreraLeonel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TP03/TP3_HerreraLeonel/Views/Shared/_NavAdminPartial.cshtml
@model TP3_HerreraLeonel.ViewModels.IndexViewModel

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadeteria</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Cadete" asp-action="Index" title="Inicio">Cadetes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Pedido" asp-action="Index" title="Pedidos">Pedidos</a>
                    </li>
                    @if (Model.Username == "admin")
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index" title="Usuarios">Usuarios</a>
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="btn-group">
            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                    <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                </svg>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                <li>
                    <a class="dropdown-item" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                        @Model.Username
                    </a>
                </li>
                <!--
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                -->
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Logout" title="Logout">Logout</a></li>
            </ul>
        </div>
    </nav>
</header>